# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vector_service.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14vector_service.proto\x12\x0evector_service\x1a\x1bgoogle/protobuf/empty.proto\"\x1c\n\nFloatArray\x12\x0e\n\x06values\x18\x01 \x03(\x02\"V\n\tNeighbour\x12\x0c\n\x04\x64_id\x18\x01 \x01(\r\x12\x10\n\x08\x64istance\x18\x02 \x01(\x02\x12)\n\x08point_id\x18\x03 \x01(\x0b\x32\x17.vector_service.PointId\"\'\n\x07PointId\x12\r\n\x05layer\x18\x01 \x01(\r\x12\r\n\x05index\x18\x02 \x01(\x05\"F\n\rInsertRequest\x12(\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1a.vector_service.FloatArray\x12\x0b\n\x03ids\x18\x02 \x03(\r\"S\n\rSearchRequest\x12(\n\x04\x64\x61ta\x18\x01 \x03(\x0b\x32\x1a.vector_service.FloatArray\x12\x0c\n\x04knbn\x18\x02 \x01(\r\x12\n\n\x02\x65\x66\x18\x03 \x01(\r\">\n\x0cSearchResult\x12.\n\nneighbours\x18\x01 \x03(\x0b\x32\x1a.vector_service.Neighbours\":\n\nNeighbours\x12,\n\tneighbour\x18\x01 \x03(\x0b\x32\x19.vector_service.Neighbour2\x97\x01\n\rVectorService\x12?\n\x06Insert\x12\x1d.vector_service.InsertRequest\x1a\x16.google.protobuf.Empty\x12\x45\n\x06Search\x12\x1d.vector_service.SearchRequest\x1a\x1c.vector_service.SearchResultb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'vector_service_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _FLOATARRAY._serialized_start=69
  _FLOATARRAY._serialized_end=97
  _NEIGHBOUR._serialized_start=99
  _NEIGHBOUR._serialized_end=185
  _POINTID._serialized_start=187
  _POINTID._serialized_end=226
  _INSERTREQUEST._serialized_start=228
  _INSERTREQUEST._serialized_end=298
  _SEARCHREQUEST._serialized_start=300
  _SEARCHREQUEST._serialized_end=383
  _SEARCHRESULT._serialized_start=385
  _SEARCHRESULT._serialized_end=447
  _NEIGHBOURS._serialized_start=449
  _NEIGHBOURS._serialized_end=507
  _VECTORSERVICE._serialized_start=510
  _VECTORSERVICE._serialized_end=661
# @@protoc_insertion_point(module_scope)
